-- MySQL Script generated by MySQL Workbench
-- 03/04/15 11:05:43
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Events` (
  `events_ID` INT NOT NULL,
  `events_date` DATETIME NULL,
  `events_location` VARCHAR(100) NULL,
  `events_priorityLevel` INT NULL,
  `no_of_attendees` INT NULL,
  PRIMARY KEY (`events_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Member` (
  `member_ID` INT NOT NULL,
  `member_lastname` VARCHAR(45) NULL,
  `member_firstname` VARCHAR(45) NULL,
  `member_contactNo` VARCHAR(45) NULL,
  `member_homeAdd` VARCHAR(45) NULL,
  `member_emailAdd` VARCHAR(45) NULL,
  `member_actMinistry` VARCHAR(45) NULL,
  `member_attendance` VARCHAR(100) NULL,
  `Membercol` VARCHAR(45) NULL,
  PRIMARY KEY (`member_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Member_has_Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Member_has_Events` (
  `events_ID` INT NOT NULL,
  `member_ID` INT NOT NULL,
  PRIMARY KEY (`events_ID`, `member_ID`),
  INDEX `fk_Member_has_Events_Member1_idx` (`member_ID` ASC),
  CONSTRAINT `fk_Member_has_Events_Events`
    FOREIGN KEY (`events_ID`)
    REFERENCES `mydb`.`Events` (`events_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Member_has_Events_Member1`
    FOREIGN KEY (`member_ID`)
    REFERENCES `mydb`.`Member` (`member_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tithe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tithe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tithe_date` DATETIME NULL,
  `tithe_envno` VARCHAR(45) NULL,
  `tithe_amount` INT NULL,
  `tithe_total` INT NULL,
  `member_ID` INT NOT NULL,
  PRIMARY KEY (`id`, `member_ID`),
  INDEX `fk_Tithe_Member1_idx` (`member_ID` ASC),
  CONSTRAINT `fk_Tithe_Member1`
    FOREIGN KEY (`member_ID`)
    REFERENCES `mydb`.`Member` (`member_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PrayerRequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PrayerRequest` (
  `prayerRequest_ID` INT NOT NULL,
  `prayerRequest_code` INT NULL,
  `prayerRequest_type` VARCHAR(45) NULL,
  `prayerRequest_description` VARCHAR(100) NULL,
  PRIMARY KEY (`prayerRequest_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Member_gives_PrayerRequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Member_gives_PrayerRequest` (
  `prayerRequest_ID` INT NOT NULL,
  `member_ID` INT NOT NULL,
  PRIMARY KEY (`prayerRequest_ID`, `member_ID`),
  INDEX `fk_Member_gives_PrayerRequest_Member1_idx` (`member_ID` ASC),
  CONSTRAINT `fk_Member_gives_PrayerRequest_PrayerRequest1`
    FOREIGN KEY (`prayerRequest_ID`)
    REFERENCES `mydb`.`PrayerRequest` (`prayerRequest_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Member_gives_PrayerRequest_Member1`
    FOREIGN KEY (`member_ID`)
    REFERENCES `mydb`.`Member` (`member_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `id` INT NOT NULL,
  `admin_filterprayer` TINYINT(1) NULL,
  `admin_postprayer` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`filtered_prayerrequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`filtered_prayerrequest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prayerRequest_id` INT NOT NULL,
  `admin_id` INT NOT NULL,
  PRIMARY KEY (`id`, `prayerRequest_id`, `admin_id`),
  INDEX `fk_Filtered_PrayerRequest_Admin1_idx` (`admin_id` ASC),
  CONSTRAINT `fk_Filtered_PrayerRequest_PrayerRequest1`
    FOREIGN KEY (`prayerRequest_id`)
    REFERENCES `mydb`.`PrayerRequest` (`prayerRequest_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Filtered_PrayerRequest_Admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `mydb`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
