-- MySQL Script generated by MySQL Workbench
-- 04/08/15 19:42:35
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`auth_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_rule` (
  `name` VARCHAR(64) NOT NULL,
  `data` TEXT NULL DEFAULT NULL,
  `created_at` INT(11) NULL DEFAULT NULL,
  `updated_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`auth_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_item` (
  `name` VARCHAR(64) NOT NULL,
  `type` INT(11) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `rule_name` VARCHAR(64) NULL DEFAULT NULL,
  `data` TEXT NULL DEFAULT NULL,
  `created_at` INT(11) NULL DEFAULT NULL,
  `updated_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`name`),
  INDEX `type` (`type` ASC),
  INDEX `fk_{4B44A0CC-0EAD-4175-92D6-DC4249F287ED}` (`rule_name` ASC),
  CONSTRAINT `auth_item_ibfk_1`
    FOREIGN KEY (`rule_name`)
    REFERENCES `mydb`.`auth_rule` (`name`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_{4B44A0CC-0EAD-4175-92D6-DC4249F287ED}`
    FOREIGN KEY (`rule_name`)
    REFERENCES `mydb`.`auth_rule` (`name`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`auth_assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_assignment` (
  `item_name` VARCHAR(64) NOT NULL,
  `user_id` VARCHAR(64) NOT NULL,
  `created_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`item_name`, `user_id`),
  CONSTRAINT `fk_{4C192318-B4C2-4B06-9A5F-085F50194A45}`
    FOREIGN KEY (`item_name`)
    REFERENCES `mydb`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`auth_item_child`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_item_child` (
  `parent` VARCHAR(64) NOT NULL,
  `child` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`parent`, `child`),
  INDEX `fk_{D3E7AA73-43BE-48A2-B391-64DF2610474E}` (`child` ASC),
  CONSTRAINT `fk_{ABA01DD3-D817-414E-8A97-3E86FE8A80C4}`
    FOREIGN KEY (`parent`)
    REFERENCES `mydb`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_{D3E7AA73-43BE-48A2-B391-64DF2610474E}`
    FOREIGN KEY (`child`)
    REFERENCES `mydb`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`events` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `events_date` DATE NULL DEFAULT NULL,
  `events_location` VARCHAR(100) NULL DEFAULT NULL,
  `events_prioritylevel` VARCHAR(10) NULL DEFAULT NULL,
  `event_desc` VARCHAR(255) NULL DEFAULT NULL,
  `no_of_attendees` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`migration` (
  `version` VARCHAR(180) NOT NULL,
  `apply_time` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `auth_key` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `password_hash` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `password_reset_token` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `status` SMALLINT(6) NULL DEFAULT '10',
  `created_at` INT(11) NULL DEFAULT NULL,
  `updated_at` INT(11) NULL DEFAULT NULL,
  `user_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `user_contactno` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `user_homeadd` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `user_actministry` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `user_attendance` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`prayer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prayer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `prayer_desc` VARCHAR(100) NULL DEFAULT NULL,
  `prayer_code` VARCHAR(10) NOT NULL,
  `prayer_schedule` DATE NULL,
  `prayer_status` VARCHAR(45) NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_member_gives_prayerrequest_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_member_gives_prayerrequest_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`tithe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tithe` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tithe_date` DATE NULL DEFAULT NULL,
  `tithe_envno` VARCHAR(45) NULL DEFAULT NULL,
  `tithe_amount` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_tithe_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_tithe_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_events` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `events_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `events_id`, `user_id`),
  INDEX `fk_member_has_events_user1_idx` (`user_id` ASC),
  INDEX `fk_Member_has_Events_Events` (`events_id` ASC),
  CONSTRAINT `fk_Member_has_Events_Events`
    FOREIGN KEY (`events_id`)
    REFERENCES `mydb`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_has_events_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`prayer_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prayer_type` (
  `id` INT NOT NULL,
  `prayer_type` VARCHAR(45) NULL,
  `prayer_id` INT(11) NOT NULL,
  `prayer_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `prayer_id`, `prayer_user_id`),
  INDEX `fk_prayer_type_prayer1_idx` (`prayer_id` ASC, `prayer_user_id` ASC),
  CONSTRAINT `fk_prayer_type_prayer1`
    FOREIGN KEY (`prayer_id` , `prayer_user_id`)
    REFERENCES `mydb`.`prayer` (`id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
