-- MySQL Script generated by MySQL Workbench
-- 03/29/15 20:00:06
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mbc_rts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mbc_rts` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mbc_rts` ;

-- -----------------------------------------------------
-- Table `mbc_rts`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbc_rts`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `events_date` DATE NULL,
  `events_location` VARCHAR(100) NULL,
  `events_prioritylevel` VARCHAR(10) NULL,
  `event_desc` VARCHAR(255) NULL,
  `no_of_attendees` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbc_rts`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbc_rts`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `auth_key` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `password_hash` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `password_reset_token` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `status` SMALLINT(6) NULL DEFAULT '10',
  `created_at` INT(11) NULL,
  `updated_at` INT(11) NULL,
  `user_lastname` VARCHAR(45) NULL,
  `user_firstname` VARCHAR(45) NULL,
  `user_contactno` VARCHAR(45) NULL,
  `user_homeadd` VARCHAR(45) NULL,
  `user_actministry` VARCHAR(45) NULL,
  `user_attendance` VARCHAR(45) NULL,
  `user_type` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mbc_rts`.`user_has_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbc_rts`.`user_has_events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `events_id` INT NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `events_id`, `user_id`),
  INDEX `fk_member_has_events_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Member_has_Events_Events`
    FOREIGN KEY (`events_id`)
    REFERENCES `mbc_rts`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_has_events_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mbc_rts`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbc_rts`.`tithe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbc_rts`.`tithe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tithe_date` DATE NULL,
  `tithe_envno` VARCHAR(45) NULL,
  `tithe_amount` INT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_tithe_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_tithe_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mbc_rts`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbc_rts`.`prayer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbc_rts`.`prayer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prayerrequest_code` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbc_rts`.`user_gives_prayer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbc_rts`.`user_gives_prayer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prayerrequest_id` INT NOT NULL,
  `member_gives_prayerrequest_description` VARCHAR(100) NULL,
  `prayerrequest_type` VARCHAR(45) NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `prayerrequest_id`, `user_id`),
  INDEX `fk_member_gives_prayerrequest_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Member_gives_PrayerRequest_PrayerRequest1`
    FOREIGN KEY (`prayerrequest_id`)
    REFERENCES `mbc_rts`.`prayer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_gives_prayerrequest_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mbc_rts`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbc_rts`.`migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbc_rts`.`migration` (
  `version` VARCHAR(180) NOT NULL,
  `apply_time` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
